/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.models.shipment.Shipment
import org.example.models.shipment.ShipmentType.DOMESTIC_BUSINESS

fun List<Int>.isTooLarge(): Boolean {
  return sum().toDouble() > size
}

fun onlyRunIfBusinessShipment(shipment: Shipment, businessFunction: (Shipment) -> Unit) {
  if (shipment.shipmentType == DOMESTIC_BUSINESS) businessFunction(shipment) else Unit
}

fun Shipment.lambdaWithReceiver(extensionFunction: Shipment.() -> Unit) {
  this.extensionFunction()
}

fun main() {
  //  Example 0: Extension function
  println("Is too large: ${listOf(1, 2, 3, 4, 5).isTooLarge()}")

  val businessShipment = Shipment(shipmentType = DOMESTIC_BUSINESS, id = "123")

  //  Example 1: "ugly" lambda
  onlyRunIfBusinessShipment(businessShipment) { println("$it is a business shipment") }

  // Example 2: lambda with receiver
  businessShipment.lambdaWithReceiver { println("$this is a business shipment") }
}
