/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.example.models.EvaluationResult
import org.example.models.LeaveOnDoor
import org.example.models.shipment.AdditionalService.EXPRESS_DELIVERY
import org.example.models.shipment.Shipment
import org.example.models.shipment.ShipmentType.DOMESTIC_C2C

class RulesTest {
  @Test
  fun `it should allow LeaveOnDoor when everything is in order`() {
    val shipment =
      Shipment(
        id = "123",
        shipmentType = DOMESTIC_C2C,
        payedForServices = listOf(EXPRESS_DELIVERY),
        events = emptyList(),
      )

    val result: EvaluationResult = RuleService.evaluate(shipment)

    assertTrue(result.disallowedActions.isEmpty())
    assertEquals(1, result.allowedActions.size)
    assertEquals(result.allowedActions.first(), LeaveOnDoor)
  }
}
